### ISSUE TITLE
Order of @import-ing files changes randomly

### ISSUE THREAD

**Issue by bencergazda** [jgranstrom/sass-extract#13]
It looks like sometimes the order of `@import`-s are changing randomly:

	D:\localhost\sass-extract-loader-master\examples\basics>npm start

	> sass-extract-loader-example-basics@1.0.0 start D:\Downloads\sass-extract-loader-master\examples\basics
	> webpack 1>/dev/null && node dist/app.bundle

	--- Style Varibles ---

	global:
	  $value:
		type:        SassString
		value:       OK
		sources:
		  - D:/localhost/sass-extract-loader-master/examples/basics/src/_style1.scss
		  - D:/localhost/sass-extract-loader-master/examples/basics/src/_style2.scss
		expressions:
		  - 'OK'
		  - 'NOT OK'

	D:\localhost\sass-extract-loader-master\examples\basics>npm start

	> sass-extract-loader-example-basics@1.0.0 start D:\localhost\sass-extract-loader-master\examples\basics
	> webpack 1>/dev/null && node dist/app.bundle

	--- Style Varibles ---

	global:
	  $value:
		type:        SassString
		value:       NOT OK
		sources:
		  - D:/localhost/sass-extract-loader-master/examples/basics/src/_style2.scss
		  - D:/localhost/sass-extract-loader-master/examples/basics/src/_style1.scss
		expressions:
		  - 'NOT OK'
		  - 'OK'

The content of style.scss:
	
	@import "style1";
	@import "style2";

The content of _style1.scss:
	
	$value: 'NOT OK';

The content of _style2.scss:
	
	$value: 'OK';

It should return 'OK' as the value of $value, but as it can be seen, _style2.scss gets loaded before _style1.scss in the second run.

(I'm not sure, whether this is an issue with sass-extract or sass-extract-loader. I used `sass-extract-loader`'s "Basic" example)

**Comment by jgranstrom** [comment]
@bencergazda there was an undefined behavior bug related to the order of the extracted variables that in my tests appeared about once every 20 run (but this can be completely random). This is now fixed in `0.5.3`, thank you for finding and reporting it!
