### ISSUE TITLE
DeprecationWarning: Module Chunks

### ISSUE THREAD

**Issue by dgonzalezr** [jgranstrom/sass-extract#28]
I'm getting the following warning/error when parsing a bootstrap _variable.scss file. I'm currently working with [next.js](https://github.com/zeit/next.js)

```
 ERROR  Failed to compile with 5 errors

This dependency was not found:

* fs in ./node_modules/mkdirp/index.js, ./node_modules/node-sass/lib/extensions.js and 3 others

To install it, you can run: npm install --save fs
(node:9903) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
```

Here's my peace of code:

```
import { ThemeProvider } from 'styled-components';
import { renderSync } from 'sass-extract';

const theme = renderSync(
    {
        file: 'scss/themes/bootstrap/_variables.scss'
    },
    {
        plugins: ['sass-extract-js']
    }).vars;
```

Packages version:

```
"sass-extract": "^2.1.0",
"sass-extract-js": "^0.3.0",
"node-sass": "^4.7.2",
```

Even though the variables are parsed and I can access them in a plan JSON object, but it's a bit weird 😟

**Comment by JoaoTMDias** [comment]
Same thing happens with me!
I'm using gatsbyjs!

**Comment by jgranstrom** [comment]
The `sass-extract` library has to run in a server environment such as `node.js` and cannot be imported in the frontend application directly. When using webpack you have to install both `sass-extract` and [`sass-extract-loader`](https://github.com/jgranstrom/sass-extract-loader) and import as mentioned in the [readme](https://github.com/jgranstrom/sass-extract-loader#usage). `sass-extract` will be run by webpack during compilation on the server, and the extracted output will be exposed as an object to your application. This is the same way sass compilation works when using for example the `sass-loader`.
