### ISSUE TITLE
Support for Dart Sass (possibility for using custom implementation)

### ISSUE THREAD

**Issue by bencergazda** [jgranstrom/sass-extract#43]
@jgranstrom This should not be too difficult to implement. I would be happy to send a PR for this.

**Comment by avindra** [comment]
How terrible would something like this be?

```js
let sass;
try {
 sass = require('node-sass');
} catch(err) {
  try {
    sass = require('sass');
  } catch(err2) {
    throw new Error("Unable to find a sass implementation to use");
  }
}
```

**Comment by avindra** [comment]
FWIW, I tried symlinking `node-sass` to `sass`, and that wasn't enough. Got some other nebulous error using that approach. So, I would think supporting both might involve more than just replacing the `import` statements.

**Comment by bencergazda** [comment]
@avindra The basic implementation is ready, but unfortunately we still have some things to fix, before every test gets passed.

**Comment by avindra** [comment]
@bencergazda Thanks for the heads up. That branch is here for anyone who looking:

https://github.com/jgranstrom/sass-extract/compare/master...bencergazda:feat-dart-sass

**Comment by guoyunhe** [comment]
Would be a great feature! Thanks @bencergazda

**Comment by Aapzu** [comment]
@bencergazda what is the situation of this? Is there anything I could help with?

**Comment by bencergazda** [comment]
@Aapzu Sorry for the delay. Unfortunately, I didn't have time during the past months to fix the remaining failing tests. Any help is welcome.

Please feel free to fork https://github.com/bencergazda/sass-extract/tree/feat-dart-sass (starting from 91a9c3d9), I am going help if needed in anything.

**Comment by Athorcis** [comment]
@bencergazda I fixed the remaining failing tests, but I had to use a dirty trick https://github.com/bencergazda/sass-extract/compare/feat-dart-sass...athorcis:feat-dart-sass

**Comment by bencergazda** [comment]
@Athorcis Super, thanks! I will check the changes as soon as I have a little time.

**Comment by bencergazda** [comment]
@Athorcis I looked over the files and they seem to be OK to me. Thanks for fixing the tests! Would you open a PR in [@bencergazda/sass-extract](https://github.com/bencergazda/sass-extract/)? I might ask for documenting a few lines, but otherwise I would be happy to merge it.

**Comment by Athorcis** [comment]
Here's the PR : bencergazda/sass-extract#3

**Comment by jgranstrom** [comment]
Wow, feel free to PR

**Comment by bencergazda** [comment]
@jgranstrom Created PR #51
