### ISSUE TITLE
Include doc comments

### ISSUE THREAD

**Issue by chavlji** [jgranstrom/sass-extract#45]
I find this plugin great for documentation purposes (used in Storybook pages).

**Would it be possible to somehow add doc comments found in the preceding lines?** 

Eg:
![Screenshot 2020-11-15 at 16 02 32](https://user-images.githubusercontent.com/5729421/99188396-01774400-275c-11eb-80a0-75ba2124e3e0.jpg)

So object for this variable would also include `{... comments: ['Color for emphasized texts']}`
This would enable us to keep documentation together with code.

**Comment by maximedaoust** [comment]
Unrelated to your actual problem, but would you mind explaining how you use `sass-extract` with Storybook?

**Comment by jgranstrom** [comment]
Since we actually compile the sass source to extract variables I'm fairly sure comments are not preserved, and it would likely require traversing the source AST separately, which is not in scope.
