### ISSUE TITLE
Sass plugin usage

### ISSUE THREAD

**Issue by samuelitwaru** [jgranstrom/sass-extract#46]
Hello. Am failing to understand how to apply the plugins. Could you please provide like a code sample.

For example to output simpler css data values instead of the complex sass data structures.

Thanks

**Comment by pjho** [comment]
Here's a node script for how I use it. Pretty messy but it gets the job done.
My use case is parsing a lot of configaration and util functions and automatically generating documentation

sassExtract parses the sass input file into a readable javascript object and then i do a bunch of string manipulation/pattern matching to get values into the format I want them.

https://gist.github.com/pjho/f2ad61eea4e3d1e8052f3ba52eb0f2bf

**Comment by samuelitwaru** [comment]
Thanks alot.
