### ISSUE TITLE
Option to get variables as JS object instead of JSON

### ISSUE THREAD

**Issue by adamgruber** [jgranstrom/sass-extract#6]
First, huge props on this library, it's just what I was looking for. 👍 

I was wondering if it would be possible to add an option to get the sass variables as a JS object instead of the data structure as you have it. For example:

Instead of this:
```js
{
  "$primary": {
    "type": "SassColor",
    "value": {
      "r": 255,
      "g": 239,
      "b": 213,
      "a": 1,
      "hex": "#ffefd5"
    },
    "sources": [
      "/Users/adamgruber/Sites/sassy-styled/src/colors.scss"
    ],
    "expressions": [
      "papayawhip"
    ]
  },
  "$baseMargin": {
    "type": "SassNumber",
    "value": 4,
    "unit": "px",
    "sources": [
      "/Users/adamgruber/Sites/sassy-styled/src/colors.scss"
    ],
    "expressions": [
      "4px"
    ]
  },
  "$baseBorder": {
    "type": "SassList",
    "value": [
      {
        "type": "SassNumber",
        "value": 1,
        "unit": "px"
      },
      {
        "type": "SassString",
        "value": "solid"
      },
      {
        "type": "SassColor",
        "value": {
          "r": 0,
          "g": 0,
          "b": 0,
          "a": 1,
          "hex": "#000000"
        }
      }
    ],
    "sources": [
      "/Users/adamgruber/Sites/sassy-styled/src/colors.scss"
    ],
    "expressions": [
      "1px solid black"
    ]
  }
}
```
I'd like to get this:
```js
{
  $primary: 'rgba(255, 239, 213)',
  $baseMargin: '4px',
  $baseBorder: '1px solid rgba(0, 0, 0)'
}
```

The reason is that I'm creating an app using [styled-components](https://www.styled-components.com/) which supports themes. The themes are just plain JS objects. I have an existing style guide written in SASS and I wanted to use the variables in the style guide as the theme for my components.

I am currently able to do what I need using this library and a function I wrote to transform the sass-extract data structure to plain JS. I just thought it might be something that could be added to your library. I was thinking it could be added to the `rendered.vars.global` object as a `toJS()` function. 

Then it could be used like this:
```js
const style = require('sass-extract-loader!./theme.scss');
const theme = style.global.toJS();
/* theme ==>
{
  $primary: 'rgba(255, 239, 213)',
  $baseMargin: '4px',
  $baseBorder: '1px solid rgba(0, 0, 0)'
}
*/
```

I created [this gist](https://gist.github.com/adamgruber/3af1de1d41c6e552b79588c4c0e07936) that shows the function I'm using to do the transform.

**Comment by jgranstrom** [comment]
@adamgruber thank you for your feedback!

I understand your point and I agree that it can be useful to transform the result into other formats based on the use case. The current structure is very generic for the purpose of being able to use it in many different ways without having to parse strings and so on. The idea was that you just as you did can use that result to transform it in any way you need that fits your use case.

I am thinking about adding a feature to serialize the result where you can pass in transformation functions similar to what you have in your gist, and that might include a few bundled transformations for common formats like the one you are mentioning, which would be to just generate css-like strings from the variables. These would be css-like because it might not be valid css due to the nature of sass variables, they can be fairly arbitrary values. This feature will likely be included in a near future release. This will be similar to what is being done in #4 and will likely be released with that.

**Comment by adamgruber** [comment]
Thanks for the response. I get why you built this as you did, makes total sense. I think a feature to serialize the result would be an awesome addition.

**Comment by jeffijoe** [comment]
A `serialize` / `compact` option for the loader would be awesome. 

I completely understand why the current output is as verbose as it is, it certainly has it's uses, but an option for compact output would be awesome. Not only does it make general consumption easier, but it also makes your bundle size smaller.

Looking forward to seeing this implemented - great work on this library @jgranstrom!

**Comment by adamgruber** [comment]
I started to work on a library using my gist from above. It serializes the sass to JS. Hope to release it within the next few days.

**Comment by jeffijoe** [comment]
@adamgruber nice! Is it an intermediary loader?

**Comment by adamgruber** [comment]
@jeffijoe It's standalone right now, not a loader.

**Comment by jgranstrom** [comment]
The new plugin support from version [1.0.0](https://github.com/jgranstrom/sass-extract/releases/tag/v1.0.0) comes with a bundled `minimal` plugin that will give you a proper serialized variant of the output with support for all kinds of nested data types.

This can be used with the [loader](https://github.com/jgranstrom/sass-extract-loader) from version 1.0.0 and sass-extract from version 1.0.1.

`npm install sass-extract@1.0.1 sass-extract-loader@1.0.0`

```
const style = require('sass-extract-loader?{"plugins":["minimal"]}!./theme.scss');
/* theme ==>
{
  $primary: 'rgba(255, 239, 213)',
  $baseMargin: '4px',
  $baseBorder: '1px solid black'
}
*/
```

Go ahead and try it and see if this works in the way you need it to. You can also have a look at the [bundled plugins](https://github.com/jgranstrom/sass-extract/tree/master/src/plugins) and see if one or a combination of those is what you are looking for, or use it as a reference to create your own plugin for your specific case.

**Comment by adamgruber** [comment]
@jgranstrom Thanks for your hard work on this package. The new version is awesome and fixes all the issues I saw. Also the plugin architecture is really nice. I took the project I was working on and converted it to a plugin, [sass-extract-js](https://github.com/adamgruber/sass-extract-js). I think it works much better as a plugin instead of standalone.
