### ISSUE TITLE
Importer won't recognise partials (underscore-prefixed files)

### ISSUE THREAD

**Issue by jrencz** [jgranstrom/sass-extract#9]
In lib/importer.js, in `findImportedPath` the mechanism tries to match unknown url against all given include paths.

the mechanism doesn't seem to know what sass knows: that `foo/bar/_foo.scss` is the same as `foo/bar/foo.scss`

IMO an attempt to recognise url as partial given without leading underscore should be made.

**Comment by jgranstrom** [comment]
@jrencz this was mentioned recently [over here](https://github.com/jgranstrom/sass-extract-loader/issues/1#issuecomment-315712058). There's a fix for this already that will be published today.

**Comment by jrencz** [comment]
I checked and it works for my case. Thanks for a blazing fast fix :)
